// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: control/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageKind int32

const (
	StageKind_STAGE_KIND_UNSPECIFIED StageKind = 0
	StageKind_STAGE_KIND_SOURCE      StageKind = 1
	StageKind_STAGE_KIND_FILTER      StageKind = 2
	StageKind_STAGE_KIND_TOKENIZE    StageKind = 3
	StageKind_STAGE_KIND_WCOUNT      StageKind = 4
	StageKind_STAGE_KIND_SINK        StageKind = 5
)

// Enum value maps for StageKind.
var (
	StageKind_name = map[int32]string{
		0: "STAGE_KIND_UNSPECIFIED",
		1: "STAGE_KIND_SOURCE",
		2: "STAGE_KIND_FILTER",
		3: "STAGE_KIND_TOKENIZE",
		4: "STAGE_KIND_WCOUNT",
		5: "STAGE_KIND_SINK",
	}
	StageKind_value = map[string]int32{
		"STAGE_KIND_UNSPECIFIED": 0,
		"STAGE_KIND_SOURCE":      1,
		"STAGE_KIND_FILTER":      2,
		"STAGE_KIND_TOKENIZE":    3,
		"STAGE_KIND_WCOUNT":      4,
		"STAGE_KIND_SINK":        5,
	}
)

func (x StageKind) Enum() *StageKind {
	p := new(StageKind)
	*p = x
	return p
}

func (x StageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_control_control_proto_enumTypes[0].Descriptor()
}

func (StageKind) Type() protoreflect.EnumType {
	return &file_control_control_proto_enumTypes[0]
}

func (x StageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageKind.Descriptor instead.
func (StageKind) EnumDescriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{0}
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StageKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=control.StageKind" json:"kind,omitempty"` // which stage this process implements
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                             // replica id (e.g., "W1")
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`                         // listen address (host:port) of this worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetKind() StageKind {
	if x != nil {
		return x.Kind
	}
	return StageKind_STAGE_KIND_UNSPECIFIED
}

func (x *Hello) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hello) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DownstreamAddr string                 `protobuf:"bytes,1,opt,name=downstream_addr,json=downstreamAddr,proto3" json:"downstream_addr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetDownstreamAddr() string {
	if x != nil {
		return x.DownstreamAddr
	}
	return ""
}

type Barrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Barrier) Reset() {
	*x = Barrier{}
	mi := &file_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Barrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barrier) ProtoMessage() {}

func (x *Barrier) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barrier.ProtoReflect.Descriptor instead.
func (*Barrier) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *Barrier) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AckBarrierReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StageKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=control.StageKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Epoch         int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckBarrierReq) Reset() {
	*x = AckBarrierReq{}
	mi := &file_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckBarrierReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckBarrierReq) ProtoMessage() {}

func (x *AckBarrierReq) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckBarrierReq.ProtoReflect.Descriptor instead.
func (*AckBarrierReq) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *AckBarrierReq) GetKind() StageKind {
	if x != nil {
		return x.Kind
	}
	return StageKind_STAGE_KIND_UNSPECIFIED
}

func (x *AckBarrierReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckBarrierReq) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type AckBarrierResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckBarrierResp) Reset() {
	*x = AckBarrierResp{}
	mi := &file_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckBarrierResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckBarrierResp) ProtoMessage() {}

func (x *AckBarrierResp) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckBarrierResp.ProtoReflect.Descriptor instead.
func (*AckBarrierResp) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *AckBarrierResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_control_control_proto protoreflect.FileDescriptor

const file_control_control_proto_rawDesc = "" +
	"\n" +
	"\x15control/control.proto\x12\acontrol\"S\n" +
	"\x05Hello\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.control.StageKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"1\n" +
	"\x06Config\x12'\n" +
	"\x0fdownstream_addr\x18\x01 \x01(\tR\x0edownstreamAddr\"\x1f\n" +
	"\aBarrier\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"-\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\rAckBarrierReq\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.control.StageKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\" \n" +
	"\x0eAckBarrierResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*\x9a\x01\n" +
	"\tStageKind\x12\x1a\n" +
	"\x16STAGE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STAGE_KIND_SOURCE\x10\x01\x12\x15\n" +
	"\x11STAGE_KIND_FILTER\x10\x02\x12\x17\n" +
	"\x13STAGE_KIND_TOKENIZE\x10\x03\x12\x15\n" +
	"\x11STAGE_KIND_WCOUNT\x10\x04\x12\x13\n" +
	"\x0fSTAGE_KIND_SINK\x10\x052v\n" +
	"\bRegistry\x12+\n" +
	"\bRegister\x12\x0e.control.Hello\x1a\x0f.control.Config\x12=\n" +
	"\n" +
	"AckBarrier\x12\x16.control.AckBarrierReq\x1a\x17.control.AckBarrierResp2:\n" +
	"\x06Worker\x120\n" +
	"\x0eReceiveBarrier\x12\x10.control.Barrier\x1a\f.control.AckBBZ@github.com/knakatasf/wiki-river/internal/proto/control;controlpbb\x06proto3"

var (
	file_control_control_proto_rawDescOnce sync.Once
	file_control_control_proto_rawDescData []byte
)

func file_control_control_proto_rawDescGZIP() []byte {
	file_control_control_proto_rawDescOnce.Do(func() {
		file_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_control_proto_rawDesc), len(file_control_control_proto_rawDesc)))
	})
	return file_control_control_proto_rawDescData
}

var file_control_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_control_control_proto_goTypes = []any{
	(StageKind)(0),         // 0: control.StageKind
	(*Hello)(nil),          // 1: control.Hello
	(*Config)(nil),         // 2: control.Config
	(*Barrier)(nil),        // 3: control.Barrier
	(*Ack)(nil),            // 4: control.Ack
	(*AckBarrierReq)(nil),  // 5: control.AckBarrierReq
	(*AckBarrierResp)(nil), // 6: control.AckBarrierResp
}
var file_control_control_proto_depIdxs = []int32{
	0, // 0: control.Hello.kind:type_name -> control.StageKind
	0, // 1: control.AckBarrierReq.kind:type_name -> control.StageKind
	1, // 2: control.Registry.Register:input_type -> control.Hello
	5, // 3: control.Registry.AckBarrier:input_type -> control.AckBarrierReq
	3, // 4: control.Worker.ReceiveBarrier:input_type -> control.Barrier
	2, // 5: control.Registry.Register:output_type -> control.Config
	6, // 6: control.Registry.AckBarrier:output_type -> control.AckBarrierResp
	4, // 7: control.Worker.ReceiveBarrier:output_type -> control.Ack
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_control_control_proto_init() }
func file_control_control_proto_init() {
	if File_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_control_proto_rawDesc), len(file_control_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_control_control_proto_goTypes,
		DependencyIndexes: file_control_control_proto_depIdxs,
		EnumInfos:         file_control_control_proto_enumTypes,
		MessageInfos:      file_control_control_proto_msgTypes,
	}.Build()
	File_control_control_proto = out.File
	file_control_control_proto_goTypes = nil
	file_control_control_proto_depIdxs = nil
}
