// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: stream/stream.proto

package streampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stage_Push_FullMethodName = "/stream.Stage/Push"
)

// StageClient is the client API for Stage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StageClient interface {
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Record, Ack], error)
}

type stageClient struct {
	cc grpc.ClientConnInterface
}

func NewStageClient(cc grpc.ClientConnInterface) StageClient {
	return &stageClient{cc}
}

func (c *stageClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Record, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stage_ServiceDesc.Streams[0], Stage_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Record, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stage_PushClient = grpc.ClientStreamingClient[Record, Ack]

// StageServer is the server API for Stage service.
// All implementations must embed UnimplementedStageServer
// for forward compatibility.
type StageServer interface {
	Push(grpc.ClientStreamingServer[Record, Ack]) error
	mustEmbedUnimplementedStageServer()
}

// UnimplementedStageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStageServer struct{}

func (UnimplementedStageServer) Push(grpc.ClientStreamingServer[Record, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedStageServer) mustEmbedUnimplementedStageServer() {}
func (UnimplementedStageServer) testEmbeddedByValue()               {}

// UnsafeStageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StageServer will
// result in compilation errors.
type UnsafeStageServer interface {
	mustEmbedUnimplementedStageServer()
}

func RegisterStageServer(s grpc.ServiceRegistrar, srv StageServer) {
	// If the following call pancis, it indicates UnimplementedStageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stage_ServiceDesc, srv)
}

func _Stage_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StageServer).Push(&grpc.GenericServerStream[Record, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stage_PushServer = grpc.ClientStreamingServer[Record, Ack]

// Stage_ServiceDesc is the grpc.ServiceDesc for Stage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.Stage",
	HandlerType: (*StageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _Stage_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "stream/stream.proto",
}
